"use client"

import { useState, useEffect, useMemo, useCallback } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { PlusCircle, Trash2 } from "lucide-react"
import { useBomStore } from "@/hooks/use-bom-store"
import { useInventoryStore } from "@/hooks/use-inventory-store"
import type { BomComponentType } from "@/types/bom"
import { useOrders } from "@/contexts/order-context"
import { Bom, BomComponent, MaterialOptions, useBomContext } from "./bom-context"
import { useInventory } from "@/app/inventory-context"
import { Material } from "@/app/procurement/procurement-context"

// Extended component type to include the type field
interface ExtendedBomComponentType extends BomComponentType {
  type?: string
}

interface CreateBomDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function CreateBomDialog({ open, onOpenChange }: CreateBomDialogProps) {
  const { addBom, materialOptions = [], unitOptions = [], typeOptionsMap = {} } = useBomContext()

  const { clientProposedProductMapper } = useOrders()
  const [productName, setProductName] = useState("")
  const [autoGeneratedBomCode, setAutoGeneratedBomCode] = useState("")
  const [isActive, setIsActive] = useState(true)
  const [components, setComponents] = useState<ExtendedBomComponentType[]>([])
  const [error, setError] = useState<string | null>(null)
  const [selectedProduct, setSelectedProduct] = useState<string | undefined>(undefined)

  const getTypeOptions = (materialName: string) => {
    return Array.from(typeOptionsMap[materialName as keyof typeof typeOptionsMap] || typeOptionsMap.default || new Set())
  }

  useEffect(() => {
    const { boms } = useBomStore.getState()

    // Extract existing BOM codes and find the highest number
    const existingCodes = boms.map((bom) => {
      const match = bom.bomCode.match(/BOM-(\d+)/)
      return match ? Number.parseInt(match[1], 10) : 0
    })

    const highestNumber = Math.max(0, ...existingCodes)
    const nextNumber = highestNumber + 1

    // Format with leading zeros (e.g., BOM-001, BOM-002)
    const formattedNumber = String(nextNumber).padStart(3, "0")
    setAutoGeneratedBomCode(`BOM-${formattedNumber}`)
  }, [])

  const handleAddComponent = () => {
    setComponents([
      ...components,
      {
        materialName: "",
        quantity: 0,
        unit: "Pcs", // Default unit
        cost: 0,
        type: "Standard", // Default type
        materialId: ""
      },
    ])
  }

  const handleRemoveComponent = (index: number) => {
    setComponents(components.filter((_, i) => i !== index))
  }
  const handleComponentChange = (index: number, field: keyof ExtendedBomComponentType, value: string | number) => {
    const updatedComponents = [...components]

    if (field === "materialName") {
      const selectedItem = materialOptions.find((item) => item.name === value)
      const typeOptions = getTypeOptions(value as string)
      const defaultType = typeOptions[0] || "Standard"
      updatedComponents[index] = {
        ...updatedComponents[index],
        [field]: value as string,
        unit: selectedItem?.unit || "Pcs", // Default to Pcs if not found
        cost: selectedItem?.cost || 0,
        type: defaultType, // Set default type based on selected material
      }
    } else {
      updatedComponents[index] = {
        ...updatedComponents[index],
        [field]: value,
      }
    }

    setComponents(updatedComponents)
  }
  const materialMapper = useMemo(() => {
    return materialOptions.reduce((acc: Record<string, MaterialOptions>, curr) => {
      if (!acc[curr.materialId]) {
        acc[curr.materialId] = curr
      }
      return acc;
    }, {})
  }, [materialOptions])

  const calculateTotalCost = useCallback(() => {
    return components.reduce((total, component) => {
      return total + (materialMapper[component.materialId]?.cost || 0) * component.quantity
    }, 0)
  }, [components, materialMapper])

  const handleSubmit = () => {
    // Validation
    if (!addBom) return;
    if (!selectedProduct) {
      setError("Product name is required")
      return
    }

    if (components.length === 0) {
      setError("At least one component is required")
      return
    }

    for (const component of components) {
      if (!component.materialId || component.quantity <= 0) {
        setError("All components must have a material name and quantity greater than zero")
        return
      }
    }

    const bomPayload: Partial<Bom> = {
      productId: selectedProduct,
      status: isActive
    }, bomComponents: Partial<BomComponent>[] = components.map(item => ({
      cost: item.cost,
      materialId: item.materialId,
      quantity: item.quantity,
      type: item.type,
      unit: item.unit
    }))

    addBom(bomPayload, bomComponents).then(() => {
      // Reset form
      setSelectedProduct(undefined)
      setIsActive(true)
      setComponents([])
      setError(null)

      // Close dialog
      onOpenChange(false)
    })


  }

  const selectedProductOption: any = useMemo(() => {
    return Object.values(clientProposedProductMapper).flat().find(item => item.productId === selectedProduct)?.productId || ""
  }, [clientProposedProductMapper, selectedProduct])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[800px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create New BOM</DialogTitle>
          <DialogDescription>Define a new Bill of Materials for a product</DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {error && <div className="bg-destructive/10 text-destructive p-3 rounded-md text-sm">{error}</div>}

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="product-name">Product Name</Label>
              <Select
                value={selectedProductOption}
                onValueChange={(value) => {
                  setSelectedProduct(value)
                }}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select Product" />
                </SelectTrigger>
                <SelectContent>
                  {Object.values(clientProposedProductMapper).flat().map((item) => (
                    <SelectItem key={item.id} value={item.productId || ""}>
                      {item.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {/* <div className="space-y-2">
              <Label htmlFor="bom-code">BOM Code (Auto-generated)</Label>
              <Input id="bom-code" value={autoGeneratedBomCode} readOnly className="bg-muted" />
            </div> */}
          </div>

          <div className="flex items-center space-x-2">
            <Switch id="active-status" checked={isActive} onCheckedChange={setIsActive} />
            <Label htmlFor="active-status">Active</Label>
          </div>

          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <h4 className="text-base font-medium">Components</h4>
              <Button type="button" variant="outline" size="sm" onClick={handleAddComponent}>
                <PlusCircle className="h-4 w-4 mr-2" />
                Add Component
              </Button>
            </div>

            {components.length > 0 ? (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Material</TableHead>
                    <TableHead>Type</TableHead>
                    <TableHead>Quantity</TableHead>
                    <TableHead>Unit</TableHead>
                    <TableHead>Cost (₹)</TableHead>
                    <TableHead></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {components.map((component, index) => (
                    <TableRow key={index}>
                      <TableCell>
                        <Select
                          value={component.materialId}
                          onValueChange={(value) => handleComponentChange(index, "materialId", value)}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select material" />
                          </SelectTrigger>
                          <SelectContent>
                            {materialOptions.map((item, idx) => (
                              <SelectItem key={item.name + idx} value={item.materialId}>
                                {item.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </TableCell>
                      <TableCell>
                        <Select
                          value={component.type || "Standard"}
                          onValueChange={(value) => handleComponentChange(index, "type", value)}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select type" />
                          </SelectTrigger>
                          <SelectContent>
                            {getTypeOptions(component.materialName).map((type) => (
                              <SelectItem key={type} value={type}>
                                {type}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </TableCell>
                      <TableCell>
                        <Input
                          type="number"
                          min="0"
                          value={component.quantity || ""}
                          onChange={(e) => handleComponentChange(index, "quantity", Number(e.target.value))}
                        />
                      </TableCell>
                      <TableCell>
                        <Select
                          disabled={true}
                          value={materialMapper[component.materialId]?.unit || ""}
                          onValueChange={(value) => handleComponentChange(index, "unit", value)}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select unit" />
                          </SelectTrigger>
                          <SelectContent>
                            {unitOptions.map((unit, index) => (
                              <SelectItem key={`${unit}-${index}`} value={unit}>
                                {unit}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </TableCell>
                      <TableCell>
                        <Input
                          type="number"
                          min="0"
                          step="0.01"
                          disabled={true}
                          value={materialMapper[component.materialId]?.cost || 0}
                          onChange={(e) => handleComponentChange(index, "cost", e.target.value)}
                          className="w-full"
                        />
                      </TableCell>
                      <TableCell>
                        <Button type="button" variant="ghost" size="icon" onClick={() => handleRemoveComponent(index)}>
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            ) : (
              <div className="text-center py-4 text-muted-foreground border rounded-md">
                No components added yet. Click "Add Component" to start.
              </div>
            )}

            {components.length > 0 && (
              <div className="flex justify-end">
                <div className="bg-muted p-3 rounded-md">
                  <span className="font-medium">Total Cost: </span>
                  <span className="font-bold">₹{calculateTotalCost().toFixed(2)}</span>
                </div>
              </div>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSubmit}>Create BOM</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
