"use client"

import { useState, useEffect } from "react"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from "@/components/ui/command"
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover"
import { Check, ChevronsUpDown, PlusCircle, Trash2 } from "lucide-react"
import { cn } from "@/lib/utils"
import { useBomStore } from "@/hooks/use-bom-store"
import { useInventoryStore } from "@/hooks/use-inventory-store"
import type { BomComponentType } from "@/types/bom"

interface CreateBomDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

// Sample product list - in a real app, this would come from an API or store
const products = [
  { value: "500ml Steel Bottle", label: "500ml Steel Bottle" },
  { value: "1L Plastic Bottle", label: "1L Plastic Bottle" },
  { value: "750ml Glass Bottle", label: "750ml Glass Bottle" },
  { value: "350ml Aluminum Can", label: "350ml Aluminum Can" },
  { value: "2L PET Bottle", label: "2L PET Bottle" },
  { value: "5L Water Dispenser Bottle", label: "5L Water Dispenser Bottle" },
  { value: "Sports Bottle with Straw", label: "Sports Bottle with Straw" },
  { value: "Insulated Thermos Flask", label: "Insulated Thermos Flask" },
]

export function CreateBomDialog({ open, onOpenChange }: CreateBomDialogProps) {
  const { addBom } = useBomStore()
  const { inventoryItems } = useInventoryStore()

  const [productName, setProductName] = useState("")
  const [autoGeneratedBomCode, setAutoGeneratedBomCode] = useState("")
  const [isActive, setIsActive] = useState(true)
  const [components, setComponents] = useState<BomComponentType[]>([])
  const [error, setError] = useState<string | null>(null)
  const [openCombobox, setOpenCombobox] = useState(false)

  useEffect(() => {
    const { boms } = useBomStore.getState()

    // Extract existing BOM codes and find the highest number
    const existingCodes = boms.map((bom) => {
      const match = bom.bomCode.match(/BOM-(\d+)/)
      return match ? Number.parseInt(match[1], 10) : 0
    })

    const highestNumber = Math.max(0, ...existingCodes)
    const nextNumber = highestNumber + 1

    // Format with leading zeros (e.g., BOM-001, BOM-002)
    const formattedNumber = String(nextNumber).padStart(3, "0")
    setAutoGeneratedBomCode(`BOM-${formattedNumber}`)
  }, [])

  const handleAddComponent = () => {
    setComponents([
      ...components,
      {
        materialName: "",
        quantity: 0,
        unit: "",
        cost: 0,
      },
    ])
  }

  const handleRemoveComponent = (index: number) => {
    setComponents(components.filter((_, i) => i !== index))
  }

  const handleComponentChange = (index: number, field: keyof BomComponentType, value: string | number) => {
    const updatedComponents = [...components]

    if (field === "materialName") {
      const selectedItem = inventoryItems.find((item) => item.name === value)
      updatedComponents[index] = {
        ...updatedComponents[index],
        [field]: value as string,
        unit: selectedItem?.unit || "",
        cost: selectedItem?.cost || 0,
      }
    } else {
      updatedComponents[index] = {
        ...updatedComponents[index],
        [field]: value,
      }
    }

    setComponents(updatedComponents)
  }

  const calculateTotalCost = () => {
    return components.reduce((total, component) => {
      return total + component.cost * component.quantity
    }, 0)
  }

  const handleSubmit = () => {
    // Validation
    if (!productName.trim()) {
      setError("Product name is required")
      return
    }

    if (components.length === 0) {
      setError("At least one component is required")
      return
    }

    for (const component of components) {
      if (!component.materialName || component.quantity <= 0) {
        setError("All components must have a material name and quantity greater than zero")
        return
      }
    }

    // Add BOM
    addBom({
      id: Date.now().toString(),
      productName,
      bomCode: autoGeneratedBomCode,
      status: isActive ? "active" : "inactive",
      components,
      unitCost: calculateTotalCost(),
    })

    // Reset form
    setProductName("")
    setIsActive(true)
    setComponents([])
    setError(null)

    // Close dialog
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create New BOM</DialogTitle>
          <DialogDescription>Define a new Bill of Materials for a product</DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          {error && <div className="bg-destructive/10 text-destructive p-3 rounded-md text-sm">{error}</div>}

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="product-name">Product Name</Label>
              <Popover open={openCombobox} onOpenChange={setOpenCombobox}>
                <PopoverTrigger asChild>
                  <Button
                    variant="outline"
                    role="combobox"
                    aria-expanded={openCombobox}
                    className="w-full justify-between"
                  >
                    {productName
                      ? products.find((product) => product.value === productName)?.label
                      : "Select product..."}
                    <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-[200px] p-0">
                  <Command>
                    <CommandInput placeholder="Search product..." />
                    <CommandList>
                      <CommandEmpty>No product found.</CommandEmpty>
                      <CommandGroup>
                        {products.map((product) => (
                          <CommandItem
                            key={product.value}
                            value={product.value}
                            onSelect={(currentValue) => {
                              setProductName(currentValue === productName ? "" : currentValue)
                              setOpenCombobox(false)
                            }}
                          >
                            <Check
                              className={cn(
                                "mr-2 h-4 w-4",
                                productName === product.value ? "opacity-100" : "opacity-0",
                              )}
                            />
                            {product.label}
                          </CommandItem>
                        ))}
                      </CommandGroup>
                    </CommandList>
                  </Command>
                </PopoverContent>
              </Popover>
            </div>
            <div className="space-y-2">
              <Label htmlFor="bom-code">BOM Code (Auto-generated)</Label>
              <Input id="bom-code" value={autoGeneratedBomCode} readOnly className="bg-muted" />
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <Switch id="active-status" checked={isActive} onCheckedChange={setIsActive} />
            <Label htmlFor="active-status">Active</Label>
          </div>

          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <h4 className="text-base font-medium">Components</h4>
              <Button type="button" variant="outline" size="sm" onClick={handleAddComponent}>
                <PlusCircle className="h-4 w-4 mr-2" />
                Add Component
              </Button>
            </div>

            {components.length > 0 ? (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Material</TableHead>
                    <TableHead>Quantity</TableHead>
                    <TableHead>Unit</TableHead>
                    <TableHead>Cost</TableHead>
                    <TableHead></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {components.map((component, index) => (
                    <TableRow key={index}>
                      <TableCell>
                        <Select
                          value={component.materialName}
                          onValueChange={(value) => handleComponentChange(index, "materialName", value)}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select material" />
                          </SelectTrigger>
                          <SelectContent>
                            {inventoryItems.map((item) => (
                              <SelectItem key={item.id} value={item.name}>
                                {item.name}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </TableCell>
                      <TableCell>
                        <Input
                          type="number"
                          min="0"
                          value={component.quantity || ""}
                          onChange={(e) => handleComponentChange(index, "quantity", Number(e.target.value))}
                        />
                      </TableCell>
                      <TableCell>
                        <Input value={component.unit} readOnly />
                      </TableCell>
                      <TableCell>
                        <Input value={`₹${component.cost.toFixed(2)}`} readOnly />
                      </TableCell>
                      <TableCell>
                        <Button type="button" variant="ghost" size="icon" onClick={() => handleRemoveComponent(index)}>
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            ) : (
              <div className="text-center py-4 text-muted-foreground border rounded-md">
                No components added yet. Click "Add Component" to start.
              </div>
            )}

            {components.length > 0 && (
              <div className="flex justify-end">
                <div className="bg-muted p-3 rounded-md">
                  <span className="font-medium">Total Cost: </span>
                  <span className="font-bold">₹{calculateTotalCost().toFixed(2)}</span>
                </div>
              </div>
            )}
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleSubmit}>Create BOM</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

